apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-agent
  labels:
    app: audit-agent
    tier: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-agent
  template:
    metadata:
      labels:
        app: audit-agent
        tier: agent
    spec:
      containers:
        - name: audit-agent
          image: trahulprabhu38/nexus-audit_agent:latest
          ports:
            - containerPort: 8006
          envFrom:
            - configMapRef:
                name: nexus-config
            - secretRef:
                name: nexus-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: audit-agent
  labels:
    app: audit-agent
spec:
  selector:
    app: audit-agent
  ports:
    - port: 8006
      targetPort: 8006
  type: ClusterIP
