apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-init
          image: trahulprabhu38/nexus-db_init:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres to be ready..."
              until pg_isready -h postgres -U nexus -d academic_db; do
                sleep 2
              done
              echo "Loading schema and data..."
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d academic_db -f /schema.sql
              echo "Done."
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
